name: poultry_farm_app
description: Poultry Farm Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  fl_chart: ^0.65.0
  uuid: ^4.2.1
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  csv: ^6.0.0
  pdf: ^3.11.1
  excel: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
